#pragma once

#include "jadel_defs.h"
#include <windows.h>
namespace jadel
{
    enum
    {
        KEY_NULL = 0,
        KEY_BACKSPACE,
        KEY_TAB,
        KEY_RETURN,
        KEY_SHIFT,
        KEY_CONTROL,
        KEY_ALT,
        KEY_PAUSE,
        KEY_CAPSLOCK,
        KEY_ESCAPE,
        KEY_SPACE,
        KEY_PAGEUP,
        KEY_PAGEDOWN,
        KEY_END,
        KEY_HOME,
        KEY_LEFT,
        KEY_UP,
        KEY_RIGHT,
        KEY_DOWN,
        KEY_PRINTSCR,
        KEY_INSERT,
        KEY_DELETE,
        KEY_0,
        KEY_1,
        KEY_2,
        KEY_3,
        KEY_4,
        KEY_5,
        KEY_6,
        KEY_7,
        KEY_8,
        KEY_9,
        KEY_A,
        KEY_B,
        KEY_C,
        KEY_D,
        KEY_E,
        KEY_F,
        KEY_G,
        KEY_H,
        KEY_I,
        KEY_J,
        KEY_K,
        KEY_L,
        KEY_M,
        KEY_N,
        KEY_O,
        KEY_P,
        KEY_Q,
        KEY_R,
        KEY_S,
        KEY_T,
        KEY_U,
        KEY_V,
        KEY_W,
        KEY_X,
        KEY_Y,
        KEY_Z,
        KEY_LWIN,
        KEY_RWIN,
        KEY_APPS,
        KEY_NUMPAD0,
        KEY_NUMPAD1,
        KEY_NUMPAD2,
        KEY_NUMPAD3,
        KEY_NUMPAD4,
        KEY_NUMPAD5,
        KEY_NUMPAD6,
        KEY_NUMPAD7,
        KEY_NUMPAD8,
        KEY_NUMPAD9,
        NUM_KEYS
    };

    extern uint32 convertVKKey(WPARAM key);
}