#ifndef JADEL_H
#define JADEL_H

extern "C" int JadelMain(int argc, char** argv);

#include "jadel_array.h"
#include "jadel_binaryparser.h"
#include "jadel_carray.h"
#include "jadel_color.h"
#include "jadel_defs.h"
#include "jadel_endian.h"
#include "jadel_factory.h"
#include "jadel_file.h"
#include "jadel_graphics.h"
#include "jadel_input.h"
#include "jadel_iterator.h"
#include "jadel_keys.h"
#include "jadel_linkedlist.h"
#include "jadel_math.h"
#include "jadel_math_geometry.h"
#include "jadel_memory.h"
#include "jadel_message.h"
#include "jadel_png.h"
#include "jadel_point2i.h"
#include "jadel_rectf.h"
#include "jadel_recti.h"
#include "jadel_stack.h"
#include "jadel_stackarray.h"
#include "jadel_string.h"
#include "jadel_surface.h"
#include "jadel_timer.h"
#include "jadel_update.h"
#include "jadel_util.h"
#include "jadel_vec2.h"
#include "jadel_vec3.h"
#include "jadel_vec4.h"
#include "jadel_vector.h"
#include "jadel_mat3.h"
#include "jadel_mat4.h"
#include "jadel_window.h"

#endif